// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JS_OpenUrlNewTab() {
	// BEGIN USER CODE
    const baseURL='https://www.figma.com/file/xBLgti87dKspdYAWagDrmn/Mendix-Design-Kit?';
    let path=window.location.pathname.split("/").pop();
    let nodeID='';  

    switch(path) {    
    
    //widgets
    case 'accordions':        
        nodeID='node-id=3196-38568&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'badges':
        nodeID='node-id=2969-40739&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'badge-buttons':
        nodeID='node-id=7696-50887&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'barcode-scanners':
        nodeID='node-id=9830-149514&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'buttons':
        nodeID='node-id=207-14353&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'carousels':
        nodeID='node-id=3196-38569&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'checkboxes':
        nodeID='node-id=9830-149865&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'containers':
        nodeID='node-id=9830-149888&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'datagrid-2':
        nodeID='node-id=2070-24703&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'datagrids':
        nodeID='node-id=2070-24703&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'templategrids':
        nodeID='node-id=2070-24703&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'date-pickers':
        nodeID='node-id=9830-245000&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'dropdowns':
        nodeID='node-id=9830-245001&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'dropdown-buttons':
        nodeID='node-id=7881-52198&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'file-managers':
        nodeID='node-id=9831-245070&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'gallery':
        nodeID='node-id=3196-38573&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'groupboxes':
        nodeID='node-id=3196-38574&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'images':
        nodeID='node-id=8710-56600&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'labels':
        nodeID='node-id=8420-56568&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'layout-grids':
        nodeID='node-id=33-12&t=0yChnX3prgT4VnSV-0';
        //default figma  link
        
        break;
    case 'listviews':
        nodeID='node-id=2941-37249&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'maps':
        nodeID='node-id=3196-38570&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'menu-bars':
        nodeID='node-id=9831-248764&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'navigation-lists':
        nodeID='node-id=3049-42880&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'navigation-trees':
        nodeID='node-id=3049-42880&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'popup-menus':
        nodeID='node-id=1775-19087&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'progress-bars':
        nodeID='node-id=3196-38571&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'progress-circles':
        nodeID='node-id=9831-248794&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'radiobuttons':
        nodeID='node-id=10003-152675&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'range-sliders':
        nodeID='node-id=4730-30481&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'ratings':
        nodeID='node-id=10003-156484&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'sliders':
        nodeID='node-id=10003-154707&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'switches':
        nodeID='node-id=10003-158522&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'tables':
        nodeID='node-id=9524-71146&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'tabs':
        nodeID='node-id=1841-20013&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'texts':
        nodeID='node-id=1768-16724&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'textareas':
        nodeID='node-id=10003-160573&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'textboxes':
        nodeID='node-id=1782-18998&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'timelines':
        nodeID='node-id=3181-39129&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'tooltips':
        nodeID='node-id=2152-34265&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'treenodes':
        nodeID='node-id=3181-39130&t=fbHSMSAkQaSxVCrr-0';
        break;
    
    //bulding blocks  

    case 'alerts':
        nodeID='node-id=2049-23987&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'avatars':
        nodeID='node-id=9345-64652&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'breadcrumbs':
        nodeID='node-id=3004-40403&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'card':
        nodeID='node-id=2845-40747&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'fixedfooter':
        nodeID='node-id=4161-26320&t=fbHSMSAkQaSxVCrr-0';        
        break;
    case 'formhorizontal':
        nodeID='node-id=8420-56285&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'formvertical':
        nodeID='node-id=8420-56285&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'headerhero':
        nodeID='node-id=3077-37172&t=fbHSMSAkQaSxVCrr-0';
        break;        
    case 'lists':
        nodeID='node-id=2941-37249&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'listitems':
        nodeID='node-id=2941-37249&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'masterdetail':
        nodeID='node-id=3181-39128&t=fbHSMSAkQaSxVCrr-0';
        break;        
    case 'pageheader':
        nodeID='node-id=9391-67866&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'pageheaderimage':
        nodeID='node-id=9391-67866&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'textdetail':
        nodeID='node-id=10003-162608&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'timeline':
        nodeID='node-id=3181-39129&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'treeviews':
        nodeID='node-id=3181-39130&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'wizardarrow':
        nodeID='node-id=3181-39131&t=fbHSMSAkQaSxVCrr-0';
        break;
    case 'wizardcircle':
        nodeID='node-id=3181-39131&t=fbHSMSAkQaSxVCrr-0';
        break;
    
    //page templates

    // case 'web-dashboard-status':
    //     nodeID='node-id=2222-27236&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-dashboard-navigation':
    //     nodeID='node-id=2222-27236&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-dashboard-transactions':
    //     nodeID='node-id=2222-27236&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-dashboard-actioncenter':
    //     nodeID='node-id=2222-27236&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-dashboard-pagesetting':
    //     nodeID='node-id=2222-27236&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'detail-page-action':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'detail-page-tabs':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-detail-cards':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-detail-map':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-detail-summary':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-detail-timeline':
    //     nodeID='node-id=2222-28334&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'pt_form_centered':
    //     nodeID='node-id=1807-18023&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'pt_form_split':
    //     nodeID='node-id=1807-18023&t=X16cIrCvf5fhB1at-0';
    //     break;        
    // case 'web-grid':
    //     nodeID='node-id=1768-16727&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-grid-card':
    //     nodeID='node-id=1768-16727&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-grid-tabbed':
    //     nodeID='node-id=1768-16727&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-grid-withnavigation':
    //     nodeID='node-id=1768-16727&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-list':
    //     nodeID='node-id=2222-31609&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-list-columns':
    //     nodeID='node-id=2222-31609&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-list-filtered':
    //     nodeID='node-id=2222-31609&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-list-masterdetail':
    //     nodeID='node-id=2222-31609&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-list-status':
    //     nodeID='node-id=2222-31609&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'overview':
    //     nodeID='node-id=7282-49286&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-tabs-card':
    //     nodeID='node-id=2222-31615&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-tabs-gallery':
    //     nodeID='node-id=2222-31615&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-tabs-form':
    //     nodeID='node-id=2222-31615&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-wizard-form':
    //     nodeID='node-id=2222-31618&t=X16cIrCvf5fhB1at-0';
    //     break;
    // case 'web-wizard-form-centered':
    //     nodeID='node-id=2222-31618&t=X16cIrCvf5fhB1at-0';
    //     break;
    
    default:
        nodeID='node-id=33-12&t=0yChnX3prgT4VnSV-0';
        break;
    }
    
    return openDesignURL();
    
    function openDesignURL()
    {
        const url=baseURL+nodeID;
        if (!url) {
        return Promise.reject(new Error("Input parameter 'Url' is required"));
        }
        // Native platform
        if (navigator && navigator.product === "ReactNative") {
            const Linking = require("react-native").Linking;
            return Linking.canOpenURL(url).then(supported => {
                if (!supported) {
                    return false;
                }
                return Linking.openURL(url).then(() => true);
            });
        }
        // Hybrid platform
        if (window && window.cordova) {
            window.open(url, "_system");
            return Promise.resolve(true);
        }
        // Web platform
        if (window) {
            window.open(url , '_blank');
            return Promise.resolve(true);
        }
        return Promise.resolve(false);
    }
	// END USER CODE
}
