// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} layoutType
 * @returns {Promise.<void>}
 */
export async function JS_SwitchLayout(layoutType) {
	// BEGIN USER CODE
	
		const domElement = document.querySelector(".mx-page.layout-atlas");
		
		if(domElement==null)
		{
			return false;
		}
		else
		{
			const infoElement = document.querySelector(".infoBanner");
			if(layoutType=='standard')
			{		
				domElement.classList.remove("layout-atlas-responsive-topbar--condensed");
				document.querySelector(".toggleStandard").classList.add("active");
				document.querySelector(".toggleDense").classList.remove("active");
				
				if(infoElement!=null)
				infoElement.classList.add("hide");
			}
			else // for dense
			{
				domElement.classList.add("layout-atlas-responsive-topbar--condensed");
				document.querySelector(".toggleDense").classList.add("active");
				document.querySelector(".toggleStandard").classList.remove("active");
				
				if(infoElement!=null)
				infoElement.classList.remove("hide");
			}
			return true;
		}
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
