// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} layoutType
 * @returns {Promise.<void>}
 */
export async function JS_UpdateLayout(layoutType) {
	// BEGIN USER CODE
	let attempt=0;
	const oldpath=window.location.pathname.split("/").pop();
	setTimeout(function(){
		refreshLayout();
	}, 50);
	
	function refreshLayout () 
	{
		const domElement = document.querySelector(".mx-page.layout-atlas");	
		const newpath=window.location.pathname.split("/").pop();		
		if(attempt>=7)
		{
			toggleClass(domElement);
			return false;
		}	
		else
		{
			if(domElement==null || newpath==oldpath)
			{
				attempt++;
				setTimeout(refreshLayout,50); //retry 
			}
			else
			{
				toggleClass(domElement);
				return true;
			} 
		}		
	}
	function toggleClass(domElement)
	{
		const infoElement = document.querySelector(".infoBanner");
		if(layoutType=='dense')
		{		
			domElement.classList.add("layout-atlas-responsive-topbar--condensed");	
			if(infoElement!=null)
			infoElement.classList.remove("hide");	

		}
		else // for standard
		{
			domElement.classList.remove("layout-atlas-responsive-topbar--condensed");		
			if(infoElement!=null)
			infoElement.classList.add("hide");			

		}
	}
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
