// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package saml20.actions;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import saml20.implementation.security.SecurityHelper;
import java.io.InputStream;
import java.util.Enumeration;

public class PreValidateKeyStoreFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __keyStoreObj;
	private saml20.proxies.KeyStore keyStoreObj;
	private saml20.proxies.EncryptionKeyLength encryptionKeyLength;

	public PreValidateKeyStoreFile(IContext context, IMendixObject keyStoreObj, java.lang.String encryptionKeyLength)
	{
		super(context);
		this.__keyStoreObj = keyStoreObj;
		this.encryptionKeyLength = encryptionKeyLength == null ? null : saml20.proxies.EncryptionKeyLength.valueOf(encryptionKeyLength);
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.keyStoreObj = this.__keyStoreObj == null ? null : saml20.proxies.KeyStore.initialize(getContext(), __keyStoreObj);

		// BEGIN USER CODE
       String aliasName = keyStoreObj.getAlias();
       boolean isAliasFindInKeyStore =false;
        try (InputStream inStr = Core.getFileDocumentContent(this.getContext(), __keyStoreObj)){
            java.security.KeyStore ks = SecurityHelper.getKeystore(inStr, encryptionKeyLength);
            Enumeration<String> aliases = ks.aliases();
            while (aliases.hasMoreElements()){
                String name = aliases.nextElement();
                if(name.equals(aliasName)){
                    isAliasFindInKeyStore = true;
                    break;
                }
            }
        }
        return isAliasFindInKeyStore;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PreValidateKeyStoreFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
